services:
  bot:
    build: ./bot
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - BOT_API=123
      - DB_BOT_LINK=123
      - API_UID=149e24e4-4e9a-46a1-b60e-71cdf33634c3
      - DEBUG=False